name: quantenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=h96cf925_1
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38hef030d1_3
  - arrow-cpp=8.0.0=py38had1886b_0
  - asttokens=2.1.0=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h23ab428_5
  - aws-checksums=0.1.9=hb1e8313_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=1.0=openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - boost-cpp=1.78.0=h179ae3a_0
  - bottleneck=1.3.5=py38h67323c0_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py38h9ed2024_1003
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h6c40b1e_2
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.1.1=pyhd8ed1ab_0
  - contourpy=1.0.6=py38h98b9b1b_0
  - cryptography=38.0.1=py38hf6deb26_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.3=py38h4cd09af_1
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=py38hecd8cb5_0
  - eventkit=1.0.0=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - fftw=3.3.9=h9ed2024_1
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py38hef030d1_1
  - freetype=2.12.1=hd8bbffd_0
  - gflags=2.2.2=hb1e8313_1004
  - giflib=5.2.1=hbcb3906_2
  - glog=0.6.0=h8ac2a54_0
  - grpc-cpp=1.46.1=h067a048_0
  - ib-insync=0.9.81=pyhd8ed1ab_0
  - icu=70.1=h96cf925_0
  - idna=3.4=py38hecd8cb5_0
  - imbalanced-learn=0.7.0=py_0
  - importlib-metadata=5.1.0=pyha770c72_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=haf03e11_3719
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.1=py38hecd8cb5_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.1=py38hecd8cb5_0
  - jpeg=9e=hac89ed1_2
  - jsonschema=4.17.1=pyhd8ed1ab_0
  - jupyter_client=7.4.7=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_0
  - jupyter_core=5.0.0=py38h50d1736_0
  - jupyter_nbextensions_configurator=0.4.1=py38h50d1736_2
  - jupyter_server=1.23.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kaggle=1.5.12=pyhd8ed1ab_4
  - kiwisolver=1.4.4=py38h98b9b1b_1
  - krb5=1.19.3=hb49756b_0
  - lcms2=2.14=h90f4b2a_0
  - lerc=3.0=he49afe7_0
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcurl=7.86.0=ha585b31_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.8=h9ed2024_5
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libevent=2.1.10=h815e4d9_4
  - libffi=3.4.2=hecd8cb5_6
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libnghttp2=1.46.0=ha29bfda_0
  - libopenblas=0.3.21=h54e7dc3_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.20.1=h8346a28_0
  - libsodium=1.0.18=hbcb3906_1
  - libssh2=1.10.0=h52ee1ee_2
  - libthrift=0.15.0=h054ceb0_0
  - libtiff=4.4.0=h2cd0358_2
  - libwebp=1.2.4=hfa4350a_0
  - libwebp-base=1.2.4=h775f41a_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - lz4-c=1.9.3=he49afe7_1
  - markupsafe=2.1.1=py38hef030d1_2
  - matplotlib=3.6.2=py38h50d1736_0
  - matplotlib-base=3.6.2=py38hcb346ec_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mkl=2022.1.0=hf3af037_209
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.8=pyhd8ed1ab_0
  - nbclient=0.7.0=pyhd8ed1ab_0
  - nbconvert=7.2.5=pyhd8ed1ab_0
  - nbconvert-core=7.2.5=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.5=pyhd8ed1ab_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=hca72f7f_3
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.2=pyha770c72_1
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numexpr=2.8.4=py38h57a7bef_0
  - numpy=1.23.4=py38h57a7bef_0
  - numpy-base=1.23.4=py38hc93c6d9_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1t=hfd90126_0
  - orc=1.7.4=h9274d09_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.1=py38h07fba90_0
  - pandoc=2.19.2=h694c41f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - patsy=0.5.2=py38hecd8cb5_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py38hde71d04_1
  - pip=22.2.2=py38hecd8cb5_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - psutil=5.9.4=py38hef030d1_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=8.0.0=py38h2202ef3_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38hecd8cb5_0
  - pyrsistent=0.19.2=py38hef030d1_0
  - pysocks=1.7.1=py38_1
  - python=3.8.15=h218abb5_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytz=2022.1=py38hecd8cb5_0
  - pyyaml=6.0=py38hef030d1_5
  - re2=2022.04.01=h96cf925_0
  - readline=8.2=hca72f7f_0
  - requests=2.28.1=py38hecd8cb5_0
  - scikit-learn=1.1.3=py38he9d5cce_0
  - scipy=1.9.3=py38h1d874dc_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.0=py38hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h225ccf5_2
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h880c91c_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.2=py38hca72f7f_0
  - terminado=0.17.0=pyhd1c38e8_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5d9f67b_0
  - tornado=6.2=py38hef030d1_1
  - tqdm=4.64.1=py38hecd8cb5_0
  - typing_extensions=4.4.0=pyha770c72_0
  - unicodedata2=15.0.0=py38hef030d1_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.12=py38hecd8cb5_0
  - utf8proc=2.6.1=h9ed2024_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=hca72f7f_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.2=hcb37349_0
  - pip:
    - decorator==4.4.2
    - googlefinance==0.7
    - ipykernel==5.4.2
    - ipython==7.19.0
    - jupyter-client==6.1.7
    - jupyter-core==4.7.0
    - parso==0.8.1
    - prompt-toolkit==3.0.9
    - pygments==2.7.3
    - pyzmq==20.0.0
    - traitlets==5.0.5
prefix: /Users/kahhongtai/anaconda3/envs/quantenv
